apiVersion: v1
kind: Service
metadata:
  name: aggexp
  namespace: aggexp-system
  labels:
    app: aggexp
spec:
  type: ClusterIP
  selector:
    app: aggexp
  ports:
    - name: https
      port: 443
      targetPort: 8443
      protocol: TCP
