// Package backend is the v2 gRPC protocol between the generic
// Kubernetes-aware middleware (runtime/component/v2) and a
// resource-specific backend.
//
// v2 consolidates the stateful-middleware-refinement arc (0022-0029).
// Differences from v1 (runtime/component/proto):
//
//   - Adds Validate and Mutate RPCs (from 0020). Backends may
//     advertise supports_validation / supports_mutation; the
//     middleware invokes these after its own CEL/JSONPath admission
//     rules (0029) but before persistence.
//   - Adds watch_capability in GetSchemaResponse (from 0025); values
//     are "poll", "push", or "both". The middleware honors it as a
//     hint; it also probes at startup.
//   - No ObjectMeta ownership in the Backend: the middleware owns
//     UID, resourceVersion, managedFields, finalizers,
//     ownerReferences, labels, annotations, deletionTimestamp — per
//     the 0022 thesis. The backend serves spec+status only. (This
//     is a soft contract, not a wire-enforced one: the proto still
//     carries full JSON bytes.)
//
// JSON-bytes payloads (from 0013) are preserved so the backend can
// be written in any language without per-type codegen (0019). HTTP
// transport is additive (0026); see runtime/component/v2/httpbackend
// for an implementation of the same logical contract over HTTP+SSE.
//
// Regenerate with (from the repo root):
//
//   protoc --go_out=. --go_opt=paths=source_relative \
//     --go-grpc_out=. --go-grpc_opt=paths=source_relative \
//     runtime/component/v2/proto/backend.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: runtime/component/v2/proto/backend.proto

package componentv2pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventType int32

const (
	EventType_EVENT_UNSPECIFIED EventType = 0
	EventType_EVENT_ADDED       EventType = 1
	EventType_EVENT_MODIFIED    EventType = 2
	EventType_EVENT_DELETED     EventType = 3
	EventType_EVENT_BOOKMARK    EventType = 4
)

// Enum value maps for EventType.
var (
	EventType_name = map[int32]string{
		0: "EVENT_UNSPECIFIED",
		1: "EVENT_ADDED",
		2: "EVENT_MODIFIED",
		3: "EVENT_DELETED",
		4: "EVENT_BOOKMARK",
	}
	EventType_value = map[string]int32{
		"EVENT_UNSPECIFIED": 0,
		"EVENT_ADDED":       1,
		"EVENT_MODIFIED":    2,
		"EVENT_DELETED":     3,
		"EVENT_BOOKMARK":    4,
	}
)

func (x EventType) Enum() *EventType {
	p := new(EventType)
	*p = x
	return p
}

func (x EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_runtime_component_v2_proto_backend_proto_enumTypes[0].Descriptor()
}

func (EventType) Type() protoreflect.EnumType {
	return &file_runtime_component_v2_proto_backend_proto_enumTypes[0]
}

func (x EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventType.Descriptor instead.
func (EventType) EnumDescriptor() ([]byte, []int) {
	return file_runtime_component_v2_proto_backend_proto_rawDescGZIP(), []int{0}
}

// UserInfo mirrors k8s.io/apiserver/pkg/authentication/user.Info.
type UserInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Uid           string                 `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Groups        []string               `protobuf:"bytes,3,rep,name=groups,proto3" json:"groups,omitempty"`
	Extra         map[string]*StringList `protobuf:"bytes,4,rep,name=extra,proto3" json:"extra,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	mi := &file_runtime_component_v2_proto_backend_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_component_v2_proto_backend_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_runtime_component_v2_proto_backend_proto_rawDescGZIP(), []int{0}
}

func (x *UserInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserInfo) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *UserInfo) GetGroups() []string {
	if x != nil {
		return x.Groups
	}
	return nil
}

func (x *UserInfo) GetExtra() map[string]*StringList {
	if x != nil {
		return x.Extra
	}
	return nil
}

type StringList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []string               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringList) Reset() {
	*x = StringList{}
	mi := &file_runtime_component_v2_proto_backend_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringList) ProtoMessage() {}

func (x *StringList) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_component_v2_proto_backend_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringList.ProtoReflect.Descriptor instead.
func (*StringList) Descriptor() ([]byte, []int) {
	return file_runtime_component_v2_proto_backend_proto_rawDescGZIP(), []int{1}
}

func (x *StringList) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

type TableColumn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Format        string                 `protobuf:"bytes,3,opt,name=format,proto3" json:"format,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Priority      int32                  `protobuf:"varint,5,opt,name=priority,proto3" json:"priority,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TableColumn) Reset() {
	*x = TableColumn{}
	mi := &file_runtime_component_v2_proto_backend_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TableColumn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableColumn) ProtoMessage() {}

func (x *TableColumn) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_component_v2_proto_backend_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableColumn.ProtoReflect.Descriptor instead.
func (*TableColumn) Descriptor() ([]byte, []int) {
	return file_runtime_component_v2_proto_backend_proto_rawDescGZIP(), []int{2}
}

func (x *TableColumn) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TableColumn) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *TableColumn) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *TableColumn) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *TableColumn) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

type GetSchemaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSchemaRequest) Reset() {
	*x = GetSchemaRequest{}
	mi := &file_runtime_component_v2_proto_backend_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSchemaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSchemaRequest) ProtoMessage() {}

func (x *GetSchemaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_component_v2_proto_backend_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSchemaRequest.ProtoReflect.Descriptor instead.
func (*GetSchemaRequest) Descriptor() ([]byte, []int) {
	return file_runtime_component_v2_proto_backend_proto_rawDescGZIP(), []int{3}
}

type GetSchemaResponse struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Group      string                 `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	Version    string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Resource   string                 `protobuf:"bytes,3,opt,name=resource,proto3" json:"resource,omitempty"` // plural, lowercase
	Kind       string                 `protobuf:"bytes,4,opt,name=kind,proto3" json:"kind,omitempty"`         // CamelCase singular
	Singular   string                 `protobuf:"bytes,5,opt,name=singular,proto3" json:"singular,omitempty"` // lowercase singular
	Namespaced bool                   `protobuf:"varint,6,opt,name=namespaced,proto3" json:"namespaced,omitempty"`
	Writable   bool                   `protobuf:"varint,7,opt,name=writable,proto3" json:"writable,omitempty"`
	// Schema is either plain JSON Schema describing spec+status shape
	// (Track B, 0023) or full Kubernetes-dialect OpenAPI v3 (Track A).
	// schema_is_openapi distinguishes. The middleware defaults to
	// Track B lifting if the flag is absent.
	Schema                  []byte         `protobuf:"bytes,8,opt,name=schema,proto3" json:"schema,omitempty"`
	SchemaIsOpenapi         bool           `protobuf:"varint,9,opt,name=schema_is_openapi,json=schemaIsOpenapi,proto3" json:"schema_is_openapi,omitempty"`
	Columns                 []*TableColumn `protobuf:"bytes,10,rep,name=columns,proto3" json:"columns,omitempty"`
	RowFields               []string       `protobuf:"bytes,11,rep,name=row_fields,json=rowFields,proto3" json:"row_fields,omitempty"`
	ShortNames              []string       `protobuf:"bytes,12,rep,name=short_names,json=shortNames,proto3" json:"short_names,omitempty"`
	Categories              []string       `protobuf:"bytes,13,rep,name=categories,proto3" json:"categories,omitempty"`
	SupportsServerSideApply bool           `protobuf:"varint,14,opt,name=supports_server_side_apply,json=supportsServerSideApply,proto3" json:"supports_server_side_apply,omitempty"`
	SupportsValidation      bool           `protobuf:"varint,15,opt,name=supports_validation,json=supportsValidation,proto3" json:"supports_validation,omitempty"`
	SupportsMutation        bool           `protobuf:"varint,16,opt,name=supports_mutation,json=supportsMutation,proto3" json:"supports_mutation,omitempty"`
	// watch_capability is "poll", "push", or "both" (0025). Empty
	// defaults to "poll".
	WatchCapability string `protobuf:"bytes,17,opt,name=watch_capability,json=watchCapability,proto3" json:"watch_capability,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetSchemaResponse) Reset() {
	*x = GetSchemaResponse{}
	mi := &file_runtime_component_v2_proto_backend_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSchemaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSchemaResponse) ProtoMessage() {}

func (x *GetSchemaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_component_v2_proto_backend_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSchemaResponse.ProtoReflect.Descriptor instead.
func (*GetSchemaResponse) Descriptor() ([]byte, []int) {
	return file_runtime_component_v2_proto_backend_proto_rawDescGZIP(), []int{4}
}

func (x *GetSchemaResponse) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *GetSchemaResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *GetSchemaResponse) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *GetSchemaResponse) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *GetSchemaResponse) GetSingular() string {
	if x != nil {
		return x.Singular
	}
	return ""
}

func (x *GetSchemaResponse) GetNamespaced() bool {
	if x != nil {
		return x.Namespaced
	}
	return false
}

func (x *GetSchemaResponse) GetWritable() bool {
	if x != nil {
		return x.Writable
	}
	return false
}

func (x *GetSchemaResponse) GetSchema() []byte {
	if x != nil {
		return x.Schema
	}
	return nil
}

func (x *GetSchemaResponse) GetSchemaIsOpenapi() bool {
	if x != nil {
		return x.SchemaIsOpenapi
	}
	return false
}

func (x *GetSchemaResponse) GetColumns() []*TableColumn {
	if x != nil {
		return x.Columns
	}
	return nil
}

func (x *GetSchemaResponse) GetRowFields() []string {
	if x != nil {
		return x.RowFields
	}
	return nil
}

func (x *GetSchemaResponse) GetShortNames() []string {
	if x != nil {
		return x.ShortNames
	}
	return nil
}

func (x *GetSchemaResponse) GetCategories() []string {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *GetSchemaResponse) GetSupportsServerSideApply() bool {
	if x != nil {
		return x.SupportsServerSideApply
	}
	return false
}

func (x *GetSchemaResponse) GetSupportsValidation() bool {
	if x != nil {
		return x.SupportsValidation
	}
	return false
}

func (x *GetSchemaResponse) GetSupportsMutation() bool {
	if x != nil {
		return x.SupportsMutation
	}
	return false
}

func (x *GetSchemaResponse) GetWatchCapability() string {
	if x != nil {
		return x.WatchCapability
	}
	return ""
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *UserInfo              `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_runtime_component_v2_proto_backend_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_component_v2_proto_backend_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_runtime_component_v2_proto_backend_proto_rawDescGZIP(), []int{5}
}

func (x *GetRequest) GetUser() *UserInfo {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *GetRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *GetRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObjectJson    []byte                 `protobuf:"bytes,1,opt,name=object_json,json=objectJson,proto3" json:"object_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_runtime_component_v2_proto_backend_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_component_v2_proto_backend_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_runtime_component_v2_proto_backend_proto_rawDescGZIP(), []int{6}
}

func (x *GetResponse) GetObjectJson() []byte {
	if x != nil {
		return x.ObjectJson
	}
	return nil
}

type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *UserInfo              `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	LabelSelector string                 `protobuf:"bytes,3,opt,name=label_selector,json=labelSelector,proto3" json:"label_selector,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_runtime_component_v2_proto_backend_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_component_v2_proto_backend_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_runtime_component_v2_proto_backend_proto_rawDescGZIP(), []int{7}
}

func (x *ListRequest) GetUser() *UserInfo {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *ListRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ListRequest) GetLabelSelector() string {
	if x != nil {
		return x.LabelSelector
	}
	return ""
}

type ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemsJson     [][]byte               `protobuf:"bytes,1,rep,name=items_json,json=itemsJson,proto3" json:"items_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_runtime_component_v2_proto_backend_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_component_v2_proto_backend_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_runtime_component_v2_proto_backend_proto_rawDescGZIP(), []int{8}
}

func (x *ListResponse) GetItemsJson() [][]byte {
	if x != nil {
		return x.ItemsJson
	}
	return nil
}

type CreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *UserInfo              `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	ObjectJson    []byte                 `protobuf:"bytes,3,opt,name=object_json,json=objectJson,proto3" json:"object_json,omitempty"`
	FieldManager  string                 `protobuf:"bytes,4,opt,name=field_manager,json=fieldManager,proto3" json:"field_manager,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRequest) Reset() {
	*x = CreateRequest{}
	mi := &file_runtime_component_v2_proto_backend_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequest) ProtoMessage() {}

func (x *CreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_component_v2_proto_backend_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequest.ProtoReflect.Descriptor instead.
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return file_runtime_component_v2_proto_backend_proto_rawDescGZIP(), []int{9}
}

func (x *CreateRequest) GetUser() *UserInfo {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *CreateRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *CreateRequest) GetObjectJson() []byte {
	if x != nil {
		return x.ObjectJson
	}
	return nil
}

func (x *CreateRequest) GetFieldManager() string {
	if x != nil {
		return x.FieldManager
	}
	return ""
}

type CreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObjectJson    []byte                 `protobuf:"bytes,1,opt,name=object_json,json=objectJson,proto3" json:"object_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateResponse) Reset() {
	*x = CreateResponse{}
	mi := &file_runtime_component_v2_proto_backend_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResponse) ProtoMessage() {}

func (x *CreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_component_v2_proto_backend_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResponse.ProtoReflect.Descriptor instead.
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return file_runtime_component_v2_proto_backend_proto_rawDescGZIP(), []int{10}
}

func (x *CreateResponse) GetObjectJson() []byte {
	if x != nil {
		return x.ObjectJson
	}
	return nil
}

type UpdateRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	User             *UserInfo              `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Namespace        string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name             string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	ObjectJson       []byte                 `protobuf:"bytes,4,opt,name=object_json,json=objectJson,proto3" json:"object_json,omitempty"`
	ForceAllowCreate bool                   `protobuf:"varint,5,opt,name=force_allow_create,json=forceAllowCreate,proto3" json:"force_allow_create,omitempty"`
	FieldManager     string                 `protobuf:"bytes,6,opt,name=field_manager,json=fieldManager,proto3" json:"field_manager,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UpdateRequest) Reset() {
	*x = UpdateRequest{}
	mi := &file_runtime_component_v2_proto_backend_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRequest) ProtoMessage() {}

func (x *UpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_component_v2_proto_backend_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRequest.ProtoReflect.Descriptor instead.
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return file_runtime_component_v2_proto_backend_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateRequest) GetUser() *UserInfo {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *UpdateRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *UpdateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateRequest) GetObjectJson() []byte {
	if x != nil {
		return x.ObjectJson
	}
	return nil
}

func (x *UpdateRequest) GetForceAllowCreate() bool {
	if x != nil {
		return x.ForceAllowCreate
	}
	return false
}

func (x *UpdateRequest) GetFieldManager() string {
	if x != nil {
		return x.FieldManager
	}
	return ""
}

type UpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObjectJson    []byte                 `protobuf:"bytes,1,opt,name=object_json,json=objectJson,proto3" json:"object_json,omitempty"`
	Created       bool                   `protobuf:"varint,2,opt,name=created,proto3" json:"created,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateResponse) Reset() {
	*x = UpdateResponse{}
	mi := &file_runtime_component_v2_proto_backend_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResponse) ProtoMessage() {}

func (x *UpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_component_v2_proto_backend_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResponse.ProtoReflect.Descriptor instead.
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return file_runtime_component_v2_proto_backend_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateResponse) GetObjectJson() []byte {
	if x != nil {
		return x.ObjectJson
	}
	return nil
}

func (x *UpdateResponse) GetCreated() bool {
	if x != nil {
		return x.Created
	}
	return false
}

type ApplyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *UserInfo              `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	ObjectJson    []byte                 `protobuf:"bytes,4,opt,name=object_json,json=objectJson,proto3" json:"object_json,omitempty"`
	FieldManager  string                 `protobuf:"bytes,5,opt,name=field_manager,json=fieldManager,proto3" json:"field_manager,omitempty"`
	Force         bool                   `protobuf:"varint,6,opt,name=force,proto3" json:"force,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyRequest) Reset() {
	*x = ApplyRequest{}
	mi := &file_runtime_component_v2_proto_backend_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyRequest) ProtoMessage() {}

func (x *ApplyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_component_v2_proto_backend_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyRequest.ProtoReflect.Descriptor instead.
func (*ApplyRequest) Descriptor() ([]byte, []int) {
	return file_runtime_component_v2_proto_backend_proto_rawDescGZIP(), []int{13}
}

func (x *ApplyRequest) GetUser() *UserInfo {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *ApplyRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ApplyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ApplyRequest) GetObjectJson() []byte {
	if x != nil {
		return x.ObjectJson
	}
	return nil
}

func (x *ApplyRequest) GetFieldManager() string {
	if x != nil {
		return x.FieldManager
	}
	return ""
}

func (x *ApplyRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

type ApplyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObjectJson    []byte                 `protobuf:"bytes,1,opt,name=object_json,json=objectJson,proto3" json:"object_json,omitempty"`
	Created       bool                   `protobuf:"varint,2,opt,name=created,proto3" json:"created,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyResponse) Reset() {
	*x = ApplyResponse{}
	mi := &file_runtime_component_v2_proto_backend_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyResponse) ProtoMessage() {}

func (x *ApplyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_component_v2_proto_backend_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyResponse.ProtoReflect.Descriptor instead.
func (*ApplyResponse) Descriptor() ([]byte, []int) {
	return file_runtime_component_v2_proto_backend_proto_rawDescGZIP(), []int{14}
}

func (x *ApplyResponse) GetObjectJson() []byte {
	if x != nil {
		return x.ObjectJson
	}
	return nil
}

func (x *ApplyResponse) GetCreated() bool {
	if x != nil {
		return x.Created
	}
	return false
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *UserInfo              `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_runtime_component_v2_proto_backend_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_component_v2_proto_backend_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_runtime_component_v2_proto_backend_proto_rawDescGZIP(), []int{15}
}

func (x *DeleteRequest) GetUser() *UserInfo {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *DeleteRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *DeleteRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObjectJson    []byte                 `protobuf:"bytes,1,opt,name=object_json,json=objectJson,proto3" json:"object_json,omitempty"`
	Deleted       bool                   `protobuf:"varint,2,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_runtime_component_v2_proto_backend_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_component_v2_proto_backend_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_runtime_component_v2_proto_backend_proto_rawDescGZIP(), []int{16}
}

func (x *DeleteResponse) GetObjectJson() []byte {
	if x != nil {
		return x.ObjectJson
	}
	return nil
}

func (x *DeleteResponse) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

type WatchRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	User            *UserInfo              `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Namespace       string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	LabelSelector   string                 `protobuf:"bytes,3,opt,name=label_selector,json=labelSelector,proto3" json:"label_selector,omitempty"`
	ResourceVersion string                 `protobuf:"bytes,4,opt,name=resource_version,json=resourceVersion,proto3" json:"resource_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *WatchRequest) Reset() {
	*x = WatchRequest{}
	mi := &file_runtime_component_v2_proto_backend_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchRequest) ProtoMessage() {}

func (x *WatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_component_v2_proto_backend_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchRequest.ProtoReflect.Descriptor instead.
func (*WatchRequest) Descriptor() ([]byte, []int) {
	return file_runtime_component_v2_proto_backend_proto_rawDescGZIP(), []int{17}
}

func (x *WatchRequest) GetUser() *UserInfo {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *WatchRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *WatchRequest) GetLabelSelector() string {
	if x != nil {
		return x.LabelSelector
	}
	return ""
}

func (x *WatchRequest) GetResourceVersion() string {
	if x != nil {
		return x.ResourceVersion
	}
	return ""
}

type WatchEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          EventType              `protobuf:"varint,1,opt,name=type,proto3,enum=aggexp.component.v2.EventType" json:"type,omitempty"`
	ObjectJson    []byte                 `protobuf:"bytes,2,opt,name=object_json,json=objectJson,proto3" json:"object_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchEvent) Reset() {
	*x = WatchEvent{}
	mi := &file_runtime_component_v2_proto_backend_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchEvent) ProtoMessage() {}

func (x *WatchEvent) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_component_v2_proto_backend_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchEvent.ProtoReflect.Descriptor instead.
func (*WatchEvent) Descriptor() ([]byte, []int) {
	return file_runtime_component_v2_proto_backend_proto_rawDescGZIP(), []int{18}
}

func (x *WatchEvent) GetType() EventType {
	if x != nil {
		return x.Type
	}
	return EventType_EVENT_UNSPECIFIED
}

func (x *WatchEvent) GetObjectJson() []byte {
	if x != nil {
		return x.ObjectJson
	}
	return nil
}

// ValidateRequest carries one CREATE or UPDATE for backend-side
// admission.
type ValidateRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	User       *UserInfo              `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Namespace  string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name       string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	ObjectJson []byte                 `protobuf:"bytes,4,opt,name=object_json,json=objectJson,proto3" json:"object_json,omitempty"`
	// old_object_json is the prior state on UPDATE; empty on CREATE.
	OldObjectJson []byte `protobuf:"bytes,5,opt,name=old_object_json,json=oldObjectJson,proto3" json:"old_object_json,omitempty"`
	// operation is "CREATE" or "UPDATE".
	Operation     string `protobuf:"bytes,6,opt,name=operation,proto3" json:"operation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateRequest) Reset() {
	*x = ValidateRequest{}
	mi := &file_runtime_component_v2_proto_backend_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateRequest) ProtoMessage() {}

func (x *ValidateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_component_v2_proto_backend_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateRequest.ProtoReflect.Descriptor instead.
func (*ValidateRequest) Descriptor() ([]byte, []int) {
	return file_runtime_component_v2_proto_backend_proto_rawDescGZIP(), []int{19}
}

func (x *ValidateRequest) GetUser() *UserInfo {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *ValidateRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ValidateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ValidateRequest) GetObjectJson() []byte {
	if x != nil {
		return x.ObjectJson
	}
	return nil
}

func (x *ValidateRequest) GetOldObjectJson() []byte {
	if x != nil {
		return x.OldObjectJson
	}
	return nil
}

func (x *ValidateRequest) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

// ValidateResponse signals allow/deny. causes is populated when
// allowed=false; its items map 1:1 to field.Error entries so the
// middleware can assemble a multi-cause 422 response (per 0029's
// "single 422 wire shape" observation).
type ValidateResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Allowed bool                   `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	// reason is a short human message; ignored if causes is non-empty.
	Reason        string            `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	Causes        []*AdmissionCause `protobuf:"bytes,3,rep,name=causes,proto3" json:"causes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateResponse) Reset() {
	*x = ValidateResponse{}
	mi := &file_runtime_component_v2_proto_backend_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateResponse) ProtoMessage() {}

func (x *ValidateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_component_v2_proto_backend_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateResponse.ProtoReflect.Descriptor instead.
func (*ValidateResponse) Descriptor() ([]byte, []int) {
	return file_runtime_component_v2_proto_backend_proto_rawDescGZIP(), []int{20}
}

func (x *ValidateResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *ValidateResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *ValidateResponse) GetCauses() []*AdmissionCause {
	if x != nil {
		return x.Causes
	}
	return nil
}

type AdmissionCause struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Field   string                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Message string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// type matches Kubernetes' FieldValueInvalid / FieldValueRequired /
	// FieldValueNotSupported etc. Empty defaults to FieldValueInvalid.
	Type          string `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdmissionCause) Reset() {
	*x = AdmissionCause{}
	mi := &file_runtime_component_v2_proto_backend_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdmissionCause) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdmissionCause) ProtoMessage() {}

func (x *AdmissionCause) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_component_v2_proto_backend_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdmissionCause.ProtoReflect.Descriptor instead.
func (*AdmissionCause) Descriptor() ([]byte, []int) {
	return file_runtime_component_v2_proto_backend_proto_rawDescGZIP(), []int{21}
}

func (x *AdmissionCause) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *AdmissionCause) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AdmissionCause) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type MutateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *UserInfo              `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	ObjectJson    []byte                 `protobuf:"bytes,4,opt,name=object_json,json=objectJson,proto3" json:"object_json,omitempty"`
	OldObjectJson []byte                 `protobuf:"bytes,5,opt,name=old_object_json,json=oldObjectJson,proto3" json:"old_object_json,omitempty"`
	Operation     string                 `protobuf:"bytes,6,opt,name=operation,proto3" json:"operation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MutateRequest) Reset() {
	*x = MutateRequest{}
	mi := &file_runtime_component_v2_proto_backend_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MutateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MutateRequest) ProtoMessage() {}

func (x *MutateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_component_v2_proto_backend_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MutateRequest.ProtoReflect.Descriptor instead.
func (*MutateRequest) Descriptor() ([]byte, []int) {
	return file_runtime_component_v2_proto_backend_proto_rawDescGZIP(), []int{22}
}

func (x *MutateRequest) GetUser() *UserInfo {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *MutateRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *MutateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MutateRequest) GetObjectJson() []byte {
	if x != nil {
		return x.ObjectJson
	}
	return nil
}

func (x *MutateRequest) GetOldObjectJson() []byte {
	if x != nil {
		return x.OldObjectJson
	}
	return nil
}

func (x *MutateRequest) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

type MutateResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// mutated_object_json is the post-mutation object. Empty means
	// "no change"; callers MUST fall back to the input in that case.
	MutatedObjectJson []byte `protobuf:"bytes,1,opt,name=mutated_object_json,json=mutatedObjectJson,proto3" json:"mutated_object_json,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *MutateResponse) Reset() {
	*x = MutateResponse{}
	mi := &file_runtime_component_v2_proto_backend_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MutateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MutateResponse) ProtoMessage() {}

func (x *MutateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_component_v2_proto_backend_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MutateResponse.ProtoReflect.Descriptor instead.
func (*MutateResponse) Descriptor() ([]byte, []int) {
	return file_runtime_component_v2_proto_backend_proto_rawDescGZIP(), []int{23}
}

func (x *MutateResponse) GetMutatedObjectJson() []byte {
	if x != nil {
		return x.MutatedObjectJson
	}
	return nil
}

var File_runtime_component_v2_proto_backend_proto protoreflect.FileDescriptor

const file_runtime_component_v2_proto_backend_proto_rawDesc = "" +
	"\n" +
	"(runtime/component/v2/proto/backend.proto\x12\x13aggexp.component.v2\"\xe3\x01\n" +
	"\bUserInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\tR\x03uid\x12\x16\n" +
	"\x06groups\x18\x03 \x03(\tR\x06groups\x12>\n" +
	"\x05extra\x18\x04 \x03(\v2(.aggexp.component.v2.UserInfo.ExtraEntryR\x05extra\x1aY\n" +
	"\n" +
	"ExtraEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x125\n" +
	"\x05value\x18\x02 \x01(\v2\x1f.aggexp.component.v2.StringListR\x05value:\x028\x01\"$\n" +
	"\n" +
	"StringList\x12\x16\n" +
	"\x06values\x18\x01 \x03(\tR\x06values\"\x8b\x01\n" +
	"\vTableColumn\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x16\n" +
	"\x06format\x18\x03 \x01(\tR\x06format\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1a\n" +
	"\bpriority\x18\x05 \x01(\x05R\bpriority\"\x12\n" +
	"\x10GetSchemaRequest\"\xf1\x04\n" +
	"\x11GetSchemaResponse\x12\x14\n" +
	"\x05group\x18\x01 \x01(\tR\x05group\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x1a\n" +
	"\bresource\x18\x03 \x01(\tR\bresource\x12\x12\n" +
	"\x04kind\x18\x04 \x01(\tR\x04kind\x12\x1a\n" +
	"\bsingular\x18\x05 \x01(\tR\bsingular\x12\x1e\n" +
	"\n" +
	"namespaced\x18\x06 \x01(\bR\n" +
	"namespaced\x12\x1a\n" +
	"\bwritable\x18\a \x01(\bR\bwritable\x12\x16\n" +
	"\x06schema\x18\b \x01(\fR\x06schema\x12*\n" +
	"\x11schema_is_openapi\x18\t \x01(\bR\x0fschemaIsOpenapi\x12:\n" +
	"\acolumns\x18\n" +
	" \x03(\v2 .aggexp.component.v2.TableColumnR\acolumns\x12\x1d\n" +
	"\n" +
	"row_fields\x18\v \x03(\tR\trowFields\x12\x1f\n" +
	"\vshort_names\x18\f \x03(\tR\n" +
	"shortNames\x12\x1e\n" +
	"\n" +
	"categories\x18\r \x03(\tR\n" +
	"categories\x12;\n" +
	"\x1asupports_server_side_apply\x18\x0e \x01(\bR\x17supportsServerSideApply\x12/\n" +
	"\x13supports_validation\x18\x0f \x01(\bR\x12supportsValidation\x12+\n" +
	"\x11supports_mutation\x18\x10 \x01(\bR\x10supportsMutation\x12)\n" +
	"\x10watch_capability\x18\x11 \x01(\tR\x0fwatchCapability\"q\n" +
	"\n" +
	"GetRequest\x121\n" +
	"\x04user\x18\x01 \x01(\v2\x1d.aggexp.component.v2.UserInfoR\x04user\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\".\n" +
	"\vGetResponse\x12\x1f\n" +
	"\vobject_json\x18\x01 \x01(\fR\n" +
	"objectJson\"\x85\x01\n" +
	"\vListRequest\x121\n" +
	"\x04user\x18\x01 \x01(\v2\x1d.aggexp.component.v2.UserInfoR\x04user\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12%\n" +
	"\x0elabel_selector\x18\x03 \x01(\tR\rlabelSelector\"-\n" +
	"\fListResponse\x12\x1d\n" +
	"\n" +
	"items_json\x18\x01 \x03(\fR\titemsJson\"\xa6\x01\n" +
	"\rCreateRequest\x121\n" +
	"\x04user\x18\x01 \x01(\v2\x1d.aggexp.component.v2.UserInfoR\x04user\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x1f\n" +
	"\vobject_json\x18\x03 \x01(\fR\n" +
	"objectJson\x12#\n" +
	"\rfield_manager\x18\x04 \x01(\tR\ffieldManager\"1\n" +
	"\x0eCreateResponse\x12\x1f\n" +
	"\vobject_json\x18\x01 \x01(\fR\n" +
	"objectJson\"\xe8\x01\n" +
	"\rUpdateRequest\x121\n" +
	"\x04user\x18\x01 \x01(\v2\x1d.aggexp.component.v2.UserInfoR\x04user\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1f\n" +
	"\vobject_json\x18\x04 \x01(\fR\n" +
	"objectJson\x12,\n" +
	"\x12force_allow_create\x18\x05 \x01(\bR\x10forceAllowCreate\x12#\n" +
	"\rfield_manager\x18\x06 \x01(\tR\ffieldManager\"K\n" +
	"\x0eUpdateResponse\x12\x1f\n" +
	"\vobject_json\x18\x01 \x01(\fR\n" +
	"objectJson\x12\x18\n" +
	"\acreated\x18\x02 \x01(\bR\acreated\"\xcf\x01\n" +
	"\fApplyRequest\x121\n" +
	"\x04user\x18\x01 \x01(\v2\x1d.aggexp.component.v2.UserInfoR\x04user\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1f\n" +
	"\vobject_json\x18\x04 \x01(\fR\n" +
	"objectJson\x12#\n" +
	"\rfield_manager\x18\x05 \x01(\tR\ffieldManager\x12\x14\n" +
	"\x05force\x18\x06 \x01(\bR\x05force\"J\n" +
	"\rApplyResponse\x12\x1f\n" +
	"\vobject_json\x18\x01 \x01(\fR\n" +
	"objectJson\x12\x18\n" +
	"\acreated\x18\x02 \x01(\bR\acreated\"t\n" +
	"\rDeleteRequest\x121\n" +
	"\x04user\x18\x01 \x01(\v2\x1d.aggexp.component.v2.UserInfoR\x04user\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"K\n" +
	"\x0eDeleteResponse\x12\x1f\n" +
	"\vobject_json\x18\x01 \x01(\fR\n" +
	"objectJson\x12\x18\n" +
	"\adeleted\x18\x02 \x01(\bR\adeleted\"\xb1\x01\n" +
	"\fWatchRequest\x121\n" +
	"\x04user\x18\x01 \x01(\v2\x1d.aggexp.component.v2.UserInfoR\x04user\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12%\n" +
	"\x0elabel_selector\x18\x03 \x01(\tR\rlabelSelector\x12)\n" +
	"\x10resource_version\x18\x04 \x01(\tR\x0fresourceVersion\"a\n" +
	"\n" +
	"WatchEvent\x122\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1e.aggexp.component.v2.EventTypeR\x04type\x12\x1f\n" +
	"\vobject_json\x18\x02 \x01(\fR\n" +
	"objectJson\"\xdd\x01\n" +
	"\x0fValidateRequest\x121\n" +
	"\x04user\x18\x01 \x01(\v2\x1d.aggexp.component.v2.UserInfoR\x04user\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1f\n" +
	"\vobject_json\x18\x04 \x01(\fR\n" +
	"objectJson\x12&\n" +
	"\x0fold_object_json\x18\x05 \x01(\fR\roldObjectJson\x12\x1c\n" +
	"\toperation\x18\x06 \x01(\tR\toperation\"\x81\x01\n" +
	"\x10ValidateResponse\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12;\n" +
	"\x06causes\x18\x03 \x03(\v2#.aggexp.component.v2.AdmissionCauseR\x06causes\"T\n" +
	"\x0eAdmissionCause\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\"\xdb\x01\n" +
	"\rMutateRequest\x121\n" +
	"\x04user\x18\x01 \x01(\v2\x1d.aggexp.component.v2.UserInfoR\x04user\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1f\n" +
	"\vobject_json\x18\x04 \x01(\fR\n" +
	"objectJson\x12&\n" +
	"\x0fold_object_json\x18\x05 \x01(\fR\roldObjectJson\x12\x1c\n" +
	"\toperation\x18\x06 \x01(\tR\toperation\"@\n" +
	"\x0eMutateResponse\x12.\n" +
	"\x13mutated_object_json\x18\x01 \x01(\fR\x11mutatedObjectJson*n\n" +
	"\tEventType\x12\x15\n" +
	"\x11EVENT_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vEVENT_ADDED\x10\x01\x12\x12\n" +
	"\x0eEVENT_MODIFIED\x10\x02\x12\x11\n" +
	"\rEVENT_DELETED\x10\x03\x12\x12\n" +
	"\x0eEVENT_BOOKMARK\x10\x042\xc0\x06\n" +
	"\aBackend\x12Z\n" +
	"\tGetSchema\x12%.aggexp.component.v2.GetSchemaRequest\x1a&.aggexp.component.v2.GetSchemaResponse\x12H\n" +
	"\x03Get\x12\x1f.aggexp.component.v2.GetRequest\x1a .aggexp.component.v2.GetResponse\x12K\n" +
	"\x04List\x12 .aggexp.component.v2.ListRequest\x1a!.aggexp.component.v2.ListResponse\x12Q\n" +
	"\x06Create\x12\".aggexp.component.v2.CreateRequest\x1a#.aggexp.component.v2.CreateResponse\x12Q\n" +
	"\x06Update\x12\".aggexp.component.v2.UpdateRequest\x1a#.aggexp.component.v2.UpdateResponse\x12N\n" +
	"\x05Apply\x12!.aggexp.component.v2.ApplyRequest\x1a\".aggexp.component.v2.ApplyResponse\x12Q\n" +
	"\x06Delete\x12\".aggexp.component.v2.DeleteRequest\x1a#.aggexp.component.v2.DeleteResponse\x12M\n" +
	"\x05Watch\x12!.aggexp.component.v2.WatchRequest\x1a\x1f.aggexp.component.v2.WatchEvent0\x01\x12W\n" +
	"\bValidate\x12$.aggexp.component.v2.ValidateRequest\x1a%.aggexp.component.v2.ValidateResponse\x12Q\n" +
	"\x06Mutate\x12\".aggexp.component.v2.MutateRequest\x1a#.aggexp.component.v2.MutateResponseBLZJgithub.com/cheeseandcereal/aggexp/runtime/component/v2/proto;componentv2pbb\x06proto3"

var (
	file_runtime_component_v2_proto_backend_proto_rawDescOnce sync.Once
	file_runtime_component_v2_proto_backend_proto_rawDescData []byte
)

func file_runtime_component_v2_proto_backend_proto_rawDescGZIP() []byte {
	file_runtime_component_v2_proto_backend_proto_rawDescOnce.Do(func() {
		file_runtime_component_v2_proto_backend_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_runtime_component_v2_proto_backend_proto_rawDesc), len(file_runtime_component_v2_proto_backend_proto_rawDesc)))
	})
	return file_runtime_component_v2_proto_backend_proto_rawDescData
}

var file_runtime_component_v2_proto_backend_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_runtime_component_v2_proto_backend_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_runtime_component_v2_proto_backend_proto_goTypes = []any{
	(EventType)(0),            // 0: aggexp.component.v2.EventType
	(*UserInfo)(nil),          // 1: aggexp.component.v2.UserInfo
	(*StringList)(nil),        // 2: aggexp.component.v2.StringList
	(*TableColumn)(nil),       // 3: aggexp.component.v2.TableColumn
	(*GetSchemaRequest)(nil),  // 4: aggexp.component.v2.GetSchemaRequest
	(*GetSchemaResponse)(nil), // 5: aggexp.component.v2.GetSchemaResponse
	(*GetRequest)(nil),        // 6: aggexp.component.v2.GetRequest
	(*GetResponse)(nil),       // 7: aggexp.component.v2.GetResponse
	(*ListRequest)(nil),       // 8: aggexp.component.v2.ListRequest
	(*ListResponse)(nil),      // 9: aggexp.component.v2.ListResponse
	(*CreateRequest)(nil),     // 10: aggexp.component.v2.CreateRequest
	(*CreateResponse)(nil),    // 11: aggexp.component.v2.CreateResponse
	(*UpdateRequest)(nil),     // 12: aggexp.component.v2.UpdateRequest
	(*UpdateResponse)(nil),    // 13: aggexp.component.v2.UpdateResponse
	(*ApplyRequest)(nil),      // 14: aggexp.component.v2.ApplyRequest
	(*ApplyResponse)(nil),     // 15: aggexp.component.v2.ApplyResponse
	(*DeleteRequest)(nil),     // 16: aggexp.component.v2.DeleteRequest
	(*DeleteResponse)(nil),    // 17: aggexp.component.v2.DeleteResponse
	(*WatchRequest)(nil),      // 18: aggexp.component.v2.WatchRequest
	(*WatchEvent)(nil),        // 19: aggexp.component.v2.WatchEvent
	(*ValidateRequest)(nil),   // 20: aggexp.component.v2.ValidateRequest
	(*ValidateResponse)(nil),  // 21: aggexp.component.v2.ValidateResponse
	(*AdmissionCause)(nil),    // 22: aggexp.component.v2.AdmissionCause
	(*MutateRequest)(nil),     // 23: aggexp.component.v2.MutateRequest
	(*MutateResponse)(nil),    // 24: aggexp.component.v2.MutateResponse
	nil,                       // 25: aggexp.component.v2.UserInfo.ExtraEntry
}
var file_runtime_component_v2_proto_backend_proto_depIdxs = []int32{
	25, // 0: aggexp.component.v2.UserInfo.extra:type_name -> aggexp.component.v2.UserInfo.ExtraEntry
	3,  // 1: aggexp.component.v2.GetSchemaResponse.columns:type_name -> aggexp.component.v2.TableColumn
	1,  // 2: aggexp.component.v2.GetRequest.user:type_name -> aggexp.component.v2.UserInfo
	1,  // 3: aggexp.component.v2.ListRequest.user:type_name -> aggexp.component.v2.UserInfo
	1,  // 4: aggexp.component.v2.CreateRequest.user:type_name -> aggexp.component.v2.UserInfo
	1,  // 5: aggexp.component.v2.UpdateRequest.user:type_name -> aggexp.component.v2.UserInfo
	1,  // 6: aggexp.component.v2.ApplyRequest.user:type_name -> aggexp.component.v2.UserInfo
	1,  // 7: aggexp.component.v2.DeleteRequest.user:type_name -> aggexp.component.v2.UserInfo
	1,  // 8: aggexp.component.v2.WatchRequest.user:type_name -> aggexp.component.v2.UserInfo
	0,  // 9: aggexp.component.v2.WatchEvent.type:type_name -> aggexp.component.v2.EventType
	1,  // 10: aggexp.component.v2.ValidateRequest.user:type_name -> aggexp.component.v2.UserInfo
	22, // 11: aggexp.component.v2.ValidateResponse.causes:type_name -> aggexp.component.v2.AdmissionCause
	1,  // 12: aggexp.component.v2.MutateRequest.user:type_name -> aggexp.component.v2.UserInfo
	2,  // 13: aggexp.component.v2.UserInfo.ExtraEntry.value:type_name -> aggexp.component.v2.StringList
	4,  // 14: aggexp.component.v2.Backend.GetSchema:input_type -> aggexp.component.v2.GetSchemaRequest
	6,  // 15: aggexp.component.v2.Backend.Get:input_type -> aggexp.component.v2.GetRequest
	8,  // 16: aggexp.component.v2.Backend.List:input_type -> aggexp.component.v2.ListRequest
	10, // 17: aggexp.component.v2.Backend.Create:input_type -> aggexp.component.v2.CreateRequest
	12, // 18: aggexp.component.v2.Backend.Update:input_type -> aggexp.component.v2.UpdateRequest
	14, // 19: aggexp.component.v2.Backend.Apply:input_type -> aggexp.component.v2.ApplyRequest
	16, // 20: aggexp.component.v2.Backend.Delete:input_type -> aggexp.component.v2.DeleteRequest
	18, // 21: aggexp.component.v2.Backend.Watch:input_type -> aggexp.component.v2.WatchRequest
	20, // 22: aggexp.component.v2.Backend.Validate:input_type -> aggexp.component.v2.ValidateRequest
	23, // 23: aggexp.component.v2.Backend.Mutate:input_type -> aggexp.component.v2.MutateRequest
	5,  // 24: aggexp.component.v2.Backend.GetSchema:output_type -> aggexp.component.v2.GetSchemaResponse
	7,  // 25: aggexp.component.v2.Backend.Get:output_type -> aggexp.component.v2.GetResponse
	9,  // 26: aggexp.component.v2.Backend.List:output_type -> aggexp.component.v2.ListResponse
	11, // 27: aggexp.component.v2.Backend.Create:output_type -> aggexp.component.v2.CreateResponse
	13, // 28: aggexp.component.v2.Backend.Update:output_type -> aggexp.component.v2.UpdateResponse
	15, // 29: aggexp.component.v2.Backend.Apply:output_type -> aggexp.component.v2.ApplyResponse
	17, // 30: aggexp.component.v2.Backend.Delete:output_type -> aggexp.component.v2.DeleteResponse
	19, // 31: aggexp.component.v2.Backend.Watch:output_type -> aggexp.component.v2.WatchEvent
	21, // 32: aggexp.component.v2.Backend.Validate:output_type -> aggexp.component.v2.ValidateResponse
	24, // 33: aggexp.component.v2.Backend.Mutate:output_type -> aggexp.component.v2.MutateResponse
	24, // [24:34] is the sub-list for method output_type
	14, // [14:24] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_runtime_component_v2_proto_backend_proto_init() }
func file_runtime_component_v2_proto_backend_proto_init() {
	if File_runtime_component_v2_proto_backend_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_runtime_component_v2_proto_backend_proto_rawDesc), len(file_runtime_component_v2_proto_backend_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_runtime_component_v2_proto_backend_proto_goTypes,
		DependencyIndexes: file_runtime_component_v2_proto_backend_proto_depIdxs,
		EnumInfos:         file_runtime_component_v2_proto_backend_proto_enumTypes,
		MessageInfos:      file_runtime_component_v2_proto_backend_proto_msgTypes,
	}.Build()
	File_runtime_component_v2_proto_backend_proto = out.File
	file_runtime_component_v2_proto_backend_proto_goTypes = nil
	file_runtime_component_v2_proto_backend_proto_depIdxs = nil
}
