// Package openapi provides helpers for composing a backend-supplied
// OpenAPI v3 schema into the generic apiserver's
// GetOpenAPIDefinitions map.
//
// The public surface is small:
//
//   - GeneratedDefinitions returns the meta/v1 + runtime + version
//     + unstructured type schemas the library's apiserver plumbing
//     requires. These are baseline definitions every component
//     server needs regardless of the resource-specific schema.
//
//   - ParseBackendSchema parses the JSON OpenAPI v3 the backend
//     shipped and stamps the x-kubernetes-group-version-kind
//     extension defensively.
//
//   - Fallback returns a preserve-unknown-fields schema for the
//     case where the backend did not ship a schema or shipped one
//     that failed to parse.
//
//   - WrapAsList synthesizes the <Kind>List envelope schema.
//
//   - Compose builds the final common.GetOpenAPIDefinitions by
//     starting from GeneratedDefinitions and adding the parsed
//     backend schema keyed at the Scheme's sample-object canonical
//     name.
//
// The key invariant (from FINDINGS/0017): the defs-map entry for
// the resource MUST be keyed at the Go canonical name of the type
// the Scheme returns from New(gvk). That name is
// scheme.UnstructuredCanonicalName or scheme.DynObjectCanonicalName
// depending on the scheme mode; callers are expected to pass the
// correct key.
//
// generated.go is the committed output of openapi-gen for the
// package set [meta/v1, runtime, unstructured, version]. It is
// regenerated by running openapi-gen against the list of input
// packages; this substrate does not re-run openapi-gen
// automatically. Bumping kube-openapi may require regeneration.
package openapi
